config:
  target: "http://localhost:3000"
  phases:
    - duration: 30
      arrivalRate: 5
      name: "Warm up"
    - duration: 60
      arrivalRate: 50
      name: "High Load"
scenarios:
  - flow:
    - get:
        url: "/rest/products/search?q="
